### ISSUE TITLE
Change gallons to liters and some other changes?

### ISSUE THREAD

**Issue by ygreq** [J-Pipe/Whole-House-Water-Monitoring#2]
Hey there! 

I integrated your project as I already had 2 flow sensors. I was using a simpler code. 

I wanted to ask you what to change considering I have the following setup what do you think the solutions would be in my case?

1. I am using liters instead of gallons as I live in Europe. Any suggestions what part of the code I should change?
2. I have a different flow sensor. Do I just change  const double GALLONS_PER_PULSE to something else instead of .075 or should I set something else as well?
3. I have 2 flow sensors. What part of code should I multiply in your opinion?

Thank you so much!!
ygreq

**Comment by J-Pipe** [comment]
I'll make some updates so it can handle Liters or Gallons.

**Comment by J-Pipe** [comment]
Ok I've updated the code.

1. In the water_flow.h file, I added a section for user-specific settings. Changing "GALLONS" to "LITERS" should be all you need to do (along with updating the water_flow.yaml unit_of_measurement labels).
2. Yes, change "USAGE_PER_PULSE" to match the specs of your flow sensor. If it is a much higher value than .075, it could take a while for the flow rate to calculate.
3. Are you using separate ESPs for each flow sensor? If so, you could probably setup the second one that same way you did the first. But in the water_flow.yaml files, update the two sensor names so the names are not duplicates.

**Comment by ygreq** [comment]
Thank you, @J-Pipe! Sorry for the late reply. I had some personal problems and then my HA broke in top of that so..

Thank you so much for the update. I am trying to implement the changes now. But I am stuck trying to calculate USAGE_PER_PULSE constant. I also wrote in the FB HA group, but I am also writing you here. Maybe with your experience, you can tell if this makes sense somehow. This is what I wrote:

I am using an YF-S Water Flow Sensor. I am interested in the amount of water (in Liters) that must flow for the water sensor to send one pulse.
It has a flow pulse of 2L/MIN=16HZ or 4L/MIN=32.5HZ or 6L/MIN=49.3HZ. It says it has the following pulse characteristic F = 7Q (l/min) +/- 5%. Info from here: https://www.hobbytronics.co.uk/datash.../sensors/YF-S201.pdf

Also considering my question, is it right to take this formula 2L/MIN=16HZ and based on this to consider the following? We have 16 Hz which means 16 pulses/min and we multiply that to 60 secs => 960 pulses in 1 minute. Considering that in 1 minute we get 2 liters and we have 960 pulses in 1 minute then we divide 2 liters into 960 pulses to get 0.00208 liters per pulse. 
Does this make sense to you? Do you think it is right?


About point 3, I am using the flow sensors in my house in the kitchen. And I have a cold water pipe and a hot water one. So I would need to integrate both on the same ESP. This is why I was asking for suggestions on how to integrate 2 water flow sensors onto 1 ESP. 

Thank you so much!
ygreq

**Comment by ygreq** [comment]
Also I am still trying to understand how water flow works, but it seems that USAGE_PER_PULSE should be a variable and not a constant. I base my deduction on the fact that for example the sensor I use, YF-S201, has a different frequency based on the flow of water. 

Here is a table:

```
Flow Range: 100L/H-/1800H-L/H
Flow (L/H) - Frezq.(Hz) 
120               16
240               32.5
360              49.3
480              65.5
600              82
720              90.2
```

I calculated for example that from the flow rate of 120 L/M to 720 L/M there is an 6 fold increase. While from 16Hz to 90.2Hz there is a 5.6375 fold increase. 

If you understand these things better, would you be so kind to comment on this?
Thank you so much!

**Comment by ygreq** [comment]
I posted these questions on the HA forum, and this is what I got :D 

`you can deal with the non-linearity in your sensor output using this very easily as you already have the lookup table: https://esphome.io/components/sensor/index.html#calibrate-linear `

This is the thread: https://community.home-assistant.io/t/using-esphome-to-build-a-water-flow-rate-meter-j-pipe-github-version/239818/2

**Comment by J-Pipe** [comment]
Well looking at that sheet, 120L/h is .03 L/s. That divided by 16Hz would be .0021 Liters per pulse, which seems extremely precise for a cheap sensor...
