### ISSUE TITLE
water_flow.h - possible changes for lower usage per pulse.

### ISSUE THREAD

**Issue by ktn7419** [J-Pipe/Whole-House-Water-Monitoring#5]
I have a GE water softener that I just integrated your routines with. However, my unit does 200 pulses/gal. I verified this as well. I changed USAGE_PER_PULSE to .005 and MINIMUM_FLOW_RATE to .001. What I find odd is that it seems that Water Running shuts off when the flow rate hits around .1 gal/min. I would have thought it could measure slower. Is it possible that the pulse_timeout needs adjustment due to higher # of pulses?  
Love your contribution. Works great.  Thank you for any recommendations.

**Comment by J-Pipe** [comment]
Where did you get the .001 GPM as the minimum flow rate? That is an extremely slow flow and I’d be surprised if it can actually measure such a small flow. What is the model of your water softener so I can look up the documentation?

**Comment by ktn7419** [comment]
Model GXSF30H and .001 a guess.

**Comment by J-Pipe** [comment]
So that is not something that you can just guess on. You need to enter the minimum flow rate of the unit, like the code says

**Comment by ktn7419** [comment]
Looking through the manual, I do not find a minimum flow rate published. It sounds like I need to know how much water must flow to start the turbine turning. I know a dripping faucet isn't enough. If the rate is N/A, only thing I can think of would be to put the unit in Diagnostics mode and slowly open a faucet until I here the audible 'click' and then measure how much water I get over 30 secs or a minute.  I did look up that 1 cup of water is .0625 gal.

**Comment by J-Pipe** [comment]
You could just slowly open a faucet until Water Running is true, and then measure how much water you get in one minute

**Comment by ktn7419** [comment]
The slowest rate I could get was 32oz in 1 minute. Any slower and it would cut off and then when the well pump would kick on and show water flow on.  Looks like .25g/min

**Comment by ktn7419** [comment]
Logbook entries much improved. I would see on/off entries even with no interruption in flow. Thank you for assistance.

**Comment by ktn7419** [comment]
Hello J-Pipe,

I am noticing something I can't explain. When a toilet gets flush early in the AM ~ 1:00, the gals used show
like .49. But say around 8:00AM or so, it shows closer to what I expect ~ 1 gal and then later flushes during
the day, all around 1gal. I've seen it more than once. I've looked at the code and I do not see where "millis()"
is defined. Is this a reserved constant?

Thanks for any insight.

Gary


Wednesday, April 13, 2022, 10:43:09 AM, you wrote:


You could just slowly open a faucet until Water Running is true, and then measure how much water you get in one minute
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>



-- 
Best regards,
 Gary's                            ***@***.***

**Comment by J-Pipe** [comment]
millies() returns the number of milliseconds since the start of the program and resets about every fifty days. 

Is your USAGE_PER_PULSE still .005? Or is it .5?

**Comment by ktn7419** [comment]
.005.  For 200 pulse/min....I might just open it up and clean the turbine.  Never cleaned since 2008

Thanks 

⁣Get BlueMail for Android ​

On May 8, 2022, 1:36 PM, at 1:36 PM, J-Pipe ***@***.***> wrote:
>millies() returns the number of milliseconds since the start of the
>program and resets about every fifty days. 
>
>Is your USAGE_PER_PULSE still .005? Or is it .5?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/J-Pipe/Whole-House-Water-Monitoring/issues/5#issuecomment-1120458451
>You are receiving this because you modified the open/close state.
>
>Message ID:
***@***.***>

**Comment by ktn7419** [comment]
Hello J-Pipe,

I wanted to let you know I did a cold start of my server and all is running fine now. The server runs
HA in Virtual Box on a Windows 10 machine.

Thanks again

Gary

Sunday, May 8, 2022, 1:36:54 PM, you wrote:


millies() returns the number of milliseconds since the start of the program and resets about every fifty days.
Is your USAGE_PER_PULSE still .005? Or is it .5?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>



-- 
Best regards,
 Gary's                            ***@***.***

**Comment by ktn7419** [comment]
Hello J-Pipe,
Thanks for quick reply. Just a guess for .001GPM.   GE Model GXSF30H. Page 17
in the Owners Manual says the display goes from 000 - 199 continual for each
gallon of water passing through.

Gary


Tuesday, April 12, 2022, 6:45:04 PM, you wrote:


Where did you get the .001 GPM as the minimum flow rate? That is an extremely slow flow and I’d be surprised if it can actually measure such a small flow. What is the model of your water softener so I can look up the documentation?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>



-- 
Best regards,
 Gary                            ***@***.***
